# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c3367818df0d54b2b27ef8a2c7a90a4d98a86411426ce932cab9a6aa9f330f41ce41700aa299bd8572f4307b0e1dcb42a53bd2c5298d3192b83378b717d0a50

test:
  secret_key_base: 45cfdc4e99c9fbec400cd01ca6bbde810166c5ce21fa654124e225d98e6cb1d12710a63da3fa69caa80d96145e410a7aea89bdad55d5bf40612587df040369db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
